- name: Set default Minikube driver
  command: "{{ item.stdout }}/bin/minikube config set vm-driver none"
  with_items:
    - "{{ user_home }}"

- name: Install socat
  package:
    name: socat
    state: present
  become: yes

- name: Pull helm-charts
  command: "git clone https://github.com/greymatter-io/helm-charts.git {{ item.stdout }}/helm-charts"
  with_items:
    - "{{ user_home }}"

- name: Set minikube alias
  lineinfile: path="{{ item.stdout }}/.bashrc" regexp='^alias minikube=\'sudo /home/ubuntu/bin/minikube\'' line='alias minikube=\'sudo /home/ubuntu/bin/minikube\'' state=present
  with_items:
    - "{{ user_home }}"

- name: Docker registry
  lineinfile: path="/lib/systemd/system/docker.service" regexp='^ExecStart=/usr/bin/dockerd' line='ExecStart=/usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock --insecure-registry 172.30.0.0/16'
  become: yes
